"""Fixed S27 core fixtures and exact-output oracle. Students do not edit this file."""

from copy import deepcopy

ACCEPTED_S26_PLAN = {
    "name": "Stormlight Rescue Trail",
    "package": {
        "id": "stormlight-core-example",
        "display_name": "Stormlight Core Example",
        "toggle_style": {
            "id": "storm-glow",
            "off_color": "blue",
            "on_color": "gold",
        },
    },
    "required_station_ids": ("north-lantern", "harbor-beacon", "summit-flare"),
    "zones": [
        {
            "id": "harbor",
            "name": "Storm Harbor",
            "stations": [
                {
                    "id": "harbor-beacon",
                    "name": "Harbor Beacon",
                    "enabled": True,
                    "coordinates": {"x": 220, "y": 320},
                    "color": "blue",
                    "toggle_style_id": "storm-glow",
                    "route_order": 1,
                    "signal_power": 3,
                    "story": {
                        "when_near": "The harbor beacon flickers through the rain.",
                        "when_interacted": "You focus the beacon across the water.",
                    },
                },
                {
                    "id": "north-lantern",
                    "name": "North Lantern",
                    "enabled": True,
                    "coordinates": {"x": 420, "y": 240},
                    "color": "blue",
                    "toggle_style_id": "storm-glow",
                    "route_order": 1,
                    "signal_power": 2,
                    "story": {
                        "when_near": "The north lantern shines through the clouds.",
                        "when_interacted": "You steady the northern light.",
                    },
                },
            ],
        },
        {
            "id": "ridge",
            "name": "Lightning Ridge",
            "stations": [
                {
                    "id": "summit-flare",
                    "name": "Summit Flare",
                    "enabled": True,
                    "coordinates": {"x": 620, "y": 180},
                    "color": "orange",
                    "route_order": 2,
                    "signal_power": 4,
                    "story": {
                        "when_near": "The summit flare waits above the clouds.",
                        "when_interacted": "You send the final signal skyward.",
                    },
                }
            ],
        },
    ],
}

SINGLE_ZONE_REDUCED_PLAN = deepcopy(ACCEPTED_S26_PLAN)
SINGLE_ZONE_REDUCED_PLAN["required_station_ids"] = (
    "north-lantern",
    "harbor-beacon",
)
SINGLE_ZONE_REDUCED_PLAN["zones"] = SINGLE_ZONE_REDUCED_PLAN["zones"][:1]

EMPTY_ZONE_PLAN = deepcopy(ACCEPTED_S26_PLAN)
EMPTY_ZONE_PLAN["required_station_ids"] = ()
EMPTY_ZONE_PLAN["zones"] = [{"id": "quiet-zone", "name": "Quiet Zone", "stations": []}]

MISSING_REQUIRED_STATION_PLAN = deepcopy(ACCEPTED_S26_PLAN)
MISSING_REQUIRED_STATION_PLAN["required_station_ids"] = (
    "north-lantern",
    "absent-station",
)

WRONG_TYPE_RECORD_PLAN = deepcopy(ACCEPTED_S26_PLAN)
WRONG_TYPE_RECORD_PLAN["zones"][0]["stations"][0]["route_order"] = "first"

DUPLICATE_ID_PLAN = deepcopy(ACCEPTED_S26_PLAN)
DUPLICATE_ID_PLAN["zones"][1]["stations"][0]["id"] = "harbor-beacon"

STABLE_ORDER_TIE_PLAN = deepcopy(ACCEPTED_S26_PLAN)

EXPECTED_DOCUMENTS = {
    "manifest": {
        "schema_version": "0.2",
        "package": {
            "id": "stormlight-core-example",
            "display_name": "Stormlight Core Example",
            "version": "0.1.0",
        },
        "compatibility": {"student_api": "0.1"},
        "toggle_styles": [
            {
                "id": "storm-glow",
                "off_color": "blue",
                "on_color": "gold",
            }
        ],
        "contributions": [
            {
                "id": "north-lantern",
                "type": "world_object",
                "path": "objects/north-lantern.yaml",
            },
            {
                "id": "harbor-beacon",
                "type": "world_object",
                "path": "objects/harbor-beacon.yaml",
            },
            {
                "id": "summit-flare",
                "type": "world_object",
                "path": "objects/summit-flare.yaml",
            },
        ],
    },
    "objects": [
        {
            "path": "objects/north-lantern.yaml",
            "document": {
                "name": "North Lantern",
                "x": 420,
                "y": 240,
                "when_near": "The north lantern shines through the clouds.",
                "when_interacted": "You steady the northern light.",
                "toggle_style_id": "storm-glow",
            },
        },
        {
            "path": "objects/harbor-beacon.yaml",
            "document": {
                "name": "Harbor Beacon",
                "x": 220,
                "y": 320,
                "when_near": "The harbor beacon flickers through the rain.",
                "when_interacted": "You focus the beacon across the water.",
                "toggle_style_id": "storm-glow",
            },
        },
        {
            "path": "objects/summit-flare.yaml",
            "document": {
                "name": "Summit Flare",
                "x": 620,
                "y": 180,
                "color": "orange",
                "when_near": "The summit flare waits above the clouds.",
                "when_interacted": "You send the final signal skyward.",
            },
        },
    ],
}
