/**
 * Build-time facts about the published student Course Kit ZIP.
 *
 * The ZIP in `public/downloads/` is generated by
 * `scripts/sync_student_downloads.py` and never hand-edited. Its
 * `course-materials.json` records the commit the kit was built from. The
 * Prepare page shows that short version so a student can compare it with the
 * "Course Kit version" line printed by `check-my-computer.py` and spot a stale
 * kit without asking.
 */
import fs from "node:fs";
import path from "node:path";
import zlib from "node:zlib";

const DOWNLOADS_DIR = path.join(process.cwd(), "public", "downloads");
const KIT_ZIP = "explore-studio-course.zip";
const MATERIALS_MEMBER = "explore-studio-course/course-materials.json";

const END_OF_CENTRAL_DIRECTORY = 0x06054b50;
const CENTRAL_DIRECTORY_ENTRY = 0x02014b50;
const LOCAL_FILE_HEADER = 0x04034b50;

/** Return one member's bytes from a ZIP archive, or null when it is absent. */
function readZipMember(archive: Buffer, memberName: string): Buffer | null {
  let end = -1;
  for (let offset = archive.length - 22; offset >= 0; offset -= 1) {
    if (archive.readUInt32LE(offset) === END_OF_CENTRAL_DIRECTORY) {
      end = offset;
      break;
    }
  }
  if (end < 0) return null;

  const entries = archive.readUInt16LE(end + 10);
  let cursor = archive.readUInt32LE(end + 16);
  for (let index = 0; index < entries; index += 1) {
    if (archive.readUInt32LE(cursor) !== CENTRAL_DIRECTORY_ENTRY) return null;
    const method = archive.readUInt16LE(cursor + 10);
    const compressedSize = archive.readUInt32LE(cursor + 20);
    const nameLength = archive.readUInt16LE(cursor + 28);
    const extraLength = archive.readUInt16LE(cursor + 30);
    const commentLength = archive.readUInt16LE(cursor + 32);
    const localOffset = archive.readUInt32LE(cursor + 42);
    const name = archive.toString("utf8", cursor + 46, cursor + 46 + nameLength);
    if (name === memberName) {
      if (archive.readUInt32LE(localOffset) !== LOCAL_FILE_HEADER) return null;
      const dataStart =
        localOffset + 30 + archive.readUInt16LE(localOffset + 26) + archive.readUInt16LE(localOffset + 28);
      const data = archive.subarray(dataStart, dataStart + compressedSize);
      if (method === 0) return Buffer.from(data);
      if (method === 8) return zlib.inflateRawSync(data);
      return null;
    }
    cursor += 46 + nameLength + extraLength + commentLength;
  }
  return null;
}

/**
 * Return the published Course Kit's short version (7 characters), exactly as
 * `check-my-computer.py` prints it on its "Course Kit version" line.
 */
export function courseKitVersion(): string {
  const archive = fs.readFileSync(path.join(DOWNLOADS_DIR, KIT_ZIP));
  const member = readZipMember(archive, MATERIALS_MEMBER);
  if (!member) throw new Error(`${KIT_ZIP} has no ${MATERIALS_MEMBER}`);
  const record = JSON.parse(member.toString("utf8")) as { course_materials_source_commit?: unknown };
  const commit = record.course_materials_source_commit;
  if (typeof commit !== "string" || !/^[0-9a-f]{40}$/.test(commit)) {
    throw new Error(`${MATERIALS_MEMBER} does not record course_materials_source_commit`);
  }
  return commit.slice(0, 7);
}
