"""Sync the public course4teen-website downloads from the canonical student ZIP.

The website must never hand-author or hand-edit the student ZIP or the
computer-readiness check: both are generated by
:mod:`scripts.build_student_zip`, which already enforces the student-safety
rules (no teacher runbooks, no engine/explore source, no secrets). This script
runs that canonical builder and copies its two public-facing outputs into
``course4teen-website/public/downloads/``:

- ``explore-studio-course.zip`` — the builder's own output, unmodified.
- ``check-my-computer.py`` — extracted byte-for-byte from that same ZIP, so the
  standalone download always matches what is inside the ZIP.

Run it whenever the course materials change and the website downloads need to
catch up:

```console
python3 scripts/sync_student_downloads.py
```
"""

from __future__ import annotations

import sys
import tempfile
import zipfile
from pathlib import Path

if __package__ in (None, ""):  # allow `python3 scripts/sync_student_downloads.py`
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.build_student_zip import ZIP_ROOT, build_student_zip

READINESS_CHECK_NAME = "check-my-computer.py"
DOWNLOADS_DIR = Path("course4teen-website/public/downloads")


def sync_student_downloads(repo_root: Path | None = None) -> dict:
    """Build the canonical student ZIP and publish it plus the readiness check.

    Returns the builder's receipt for the ZIP that was published.
    """
    root = Path(repo_root).resolve() if repo_root is not None else Path(__file__).resolve().parents[1]
    downloads_dir = root / DOWNLOADS_DIR
    downloads_dir.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory(prefix="student-downloads-") as staging:
        receipt = build_student_zip(Path(staging), source_root=root)
        archive_path = receipt["archive"]
        with zipfile.ZipFile(archive_path) as archive:
            readiness_bytes = archive.read(f"{ZIP_ROOT}/{READINESS_CHECK_NAME}")
        (downloads_dir / archive_path.name).write_bytes(archive_path.read_bytes())
        (downloads_dir / READINESS_CHECK_NAME).write_bytes(readiness_bytes)

    return receipt


def main(argv=None) -> int:
    del argv
    receipt = sync_student_downloads()
    print(f"published {DOWNLOADS_DIR / 'explore-studio-course.zip'}")
    print(f"published {DOWNLOADS_DIR / READINESS_CHECK_NAME}")
    print(f"  members: {receipt['members']}")
    print(f"  course materials commit: {receipt['course_materials_source_commit']}")
    print(f"  course platform commit:  {receipt['course_platform_commit']}")
    print(f"  sha256 (zip): {receipt['sha256']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
